sudo: required

install: true

language: java

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install wget
  - wget -O go-ipfs.tar.gz https://dist.ipfs.io/go-ipfs/v0.4.10/go-ipfs_v0.4.10_linux-amd64.tar.gz
  - tar xvfz go-ipfs.tar.gz
  - sudo mv go-ipfs/ipfs /usr/local/bin/ipfs
  - sudo chmod o+x /usr/local/bin/ipfs
  - ipfs init
  - ipfs daemon &
  - rm -Rf go-ipfs.tar.gz go-ipfs .git
  - sleep 10


script:
  - docker build -t growbit/it-registry-oracle .

after_script:
  - zip -r archive.zip .
  - ipfs add -Q archive.zip