version: '3.2'
services:
  oracle:
    image: growbit_oracle
    ports:
      - '8080:8080' # spring boot hot reload & endpoint invocation
      - '5005:5005' # jmx debugging
    build:
      context: .
      dockerfile: Dockerfile
    dns: 8.8.8.8
    environment:
      - ARGN=3
      - ARG0=me_public
      - ARG1=mark_12345
      - ARG2=mark_12345_sign_by_me_public
    volumes:
      - type: volume
        source: /home/name/.m2
        target: /root/.m2
      - type: volume
        source: ./spring-boot-app
        target: /opt/spring-boot-app
    command: /opt/cmd_abuntu.sh
  frontend:
    image: nginx
    ports:
      - '8181:80'
    volumes:
      - type: volume
        source: ./js-static-app
        target: /usr/share/nginx/html